### ISSUE TITLE
no applicable method for 'filter' applied to an object of class "NULL"

### ISSUE THREAD

**Issue by rgaiacs** [schochastics/google-trends#3]
From https://github.com/schochastics/google-trends/blob/f9c71cb2480dc1afc5887a92664c9df3760d458c/index.qmd#L121-L131

```
Execution halted
Quitting from lines 122-131 [plot_related_queries_covid] (index.qmd)
 1. ggplot2::ggplot(...)
 5. dplyr::filter(covid_tbl$related_queries, related_queries == "top")
Backtrace:
! no applicable method for 'filter' applied to an object of class "NULL"
Error in `UseMethod()`:
20/23 [plot_related_queries_covid]   
```

@schochastics if you add `index.md` we can render and skip the error.

**Comment by schochastics** [comment]
getting 429 errors atm. Will try again beginning of next week

**Comment by cviehmann** [comment]
Hi David, could you help with solving thins problem? Unfortunately, it still exists and it blocks the rendering of this wonderful tutorial. 
The easiest solution is probably to add index.md as suggested by @rgaiacs . 
Just let me know, if that is ok for you? Then, I will ask our SHK to create the md file and send you a PR.

**Comment by schochastics** [comment]
I pushed a fix of the issue reported but when I wanted to rerender the md file, I got hit with 429 again. Seems to be very restrictive rate limit? In any case, you might be able to run it now, but if I do not forget, I try to render the md over the weekend

**Comment by cviehmann** [comment]
Unfortunately, it still doesn't render. The object "related_queries" seems to still cause the problems. 

<img width="1920" height="4476" alt="Image" src="https://github.com/user-attachments/assets/39e5cd9e-af89-4c2f-a3f3-2bac771d19f2" />

**Comment by schochastics** [comment]
I see what I can do. I keep getting a 429 error :(

**Comment by rgaiacs** [comment]
I looked at this. https://github.com/schochastics/google-trends/blob/7b16279b10dea07f6a87c5bd2359c4ba9a671da2/index.qmd#L86  will raise the error

```
Error in interest_over_time(widget, comparison_item, tz) : 
  Status code was not 200. Returned status code:429
```

[Searching upstream](https://github.com/PMassicotte/gtrendsR/issues?q=429) about the `429` error results in a couple of results. [In the most recent result](https://github.com/PMassicotte/gtrendsR/issues/466), user [PMassicotte](https://github.com/PMassicotte) wrote

> Error 429 means that too many requests were sent. I am afraid that there is not much we can do about it at this time. A lot of people are experiencing the same using pytrends python package.

When we look at [pytrends](https://github.com/GeneralMills/pytrends) we read

>  This repository was archived by the owner on Apr 18, 2025. It is now read-only. 

User [Terseus](https://github.com/Terseus) wrote in issue "[Stepping out as a maintainer](https://github.com/GeneralMills/pytrends/issues/636)"

> When I started to maintain this project it was because of two reasons:
>
> - work reasons; I were using this project in a product on my past company.
> - > - ethic reasons; Google doesn't provide an API for its Google Trends data, and I though it was a shame because the data it provides can be really precious for a lot of statistical analysis (as a lot of you are aware of).
>
> [...]
>
> The second reason is more complex; over time I learned that the data returned by this Google Trends "API" is just fake: when they detect that you're a bot, something that Google is pretty good at it, it gives you slightly altered data different from the one you can see in their website.
>
> [...]
>
> As for you, the community, I'll give you my most honest advice: stop using Pytrends.
>
> Not only the data returned by Google is fake, but Pytrends itself is in a pretty bad state: the code is entangled and hard to maintain, the method it uses to query Google Trends is very old and probably tolerated by Google only because they can serve fake data whenever they want, and the test suite that I created is inadequate for the nature of the API. Also, the last commit was almost 2 years ago, so you can consider this project as completely unmaintained.
>
> If you really need this kind of data looks elsewhere; there are paid providers that uses other methods to gather the data you want. it may not be cheap but that's how our society works nowadays.

To the best of my understanding, many of what user [Terseus](https://github.com/Terseus) wrote about [pytrends](https://github.com/GeneralMills/pytrends/) also apply to [gtrendsR](https://github.com/PMassicotte/gtrendsR/).

Furthermore, [a blog post from Google published on 24 July 2025](https://developers.google.com/search/blog/2025/07/trends-api) says

> Introducing the Google Trends API (alpha): a new way to access Search Trends data
>
> We're excited to let you know that the [Google Trends API is here](https://developers.google.com/search/apis/trends)! Google Trends has been around for a long time, and the website has been the main way to access the data. Over the last years we've seen an increase in usage, and we received numerous requests for an API which wasn't available until today!
>
> The API will be available only to a very limited number of testers. If you're interested in testing, [apply to be an alpha tester](https://developers.google.com/search/apis/trends#apply).

This indicates that Google will re-enforce the measures to prevent people to "scrap" [Google Trends](https://trends.google.com/trends/).

@cviehmann my recommendation is to remove this from the list that you have for Methods Hub.

@schochastics my recommendation is to archive this repository as the `Returned status code:429` will probably persist.

**Comment by schochastics** [comment]
I agree
